#!/usr/bin/python
import sys

for fizzbuzz in range(100):  
  
    if fizzbuzz % 3 == 0:      
        print("Fizz")                                          
        continue
  
    
    elif fizzbuzz % 5 == 0:          
        print("Buzz")                                      
        continue
		
	 if fizzbuzz % 15 == 0:  
        print("FizzBuzz")                                          
        continue
		
    print(fizzbuzz) 
