#!/usr/bin/python3
# importing libraries we want to use
from bs4 import BeautifulSoup
import requests
import urllib.request
date = input("What date do you want to search?")

# do a GET request of the python downloads page
page = requests.get("http://python.org/downloads/")
# use beautiful soup to parse the page
soup = BeautifulSoup(page.content, 'html.parser')
# you can uncomment this if you want to see the whole page. Compare this against the developer tools in the site. https://jetnet.jccmi.edu/mod/page/view.php?id=1291757&inpopup=1
#print(soup.prettify())
# Here is how we can pull the version list specifically
python_versions = soup.select('.download-list-widget .list-row-container li')
for version in python_versions:
  # uncomment or comment these out so you can see what you're working with
  #print (version.select(".release-date")[0].get_text())
  # print the release date (you can use this to make sure you match the proper date in April
  if date == version.select(".release-date")[0].get_text():
    # you can use this to make sure you download the right file
    print(version.select(".release-number")[0].get_text()[7:])
    correctversion = input("What version would you like to download?")
    #if "Python 2.7.4" == version.select(".release-number")[0].get_text():
    #correctversion = version.select(".release-number")[0].get_text()[7:]
    url = "https://www.python.org/ftp/python/"+correctversion+"/Python-"+correctversion+".tar.xz"
    urllib.request.urlretrieve(url, "JessicaBreidenbaugh-Python"+correctversion+".tar.xz") 



