#!/usr/bin/python3
# importing libraries we want to use
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# prompt user to input the Target IP
target = input("[+] Enter Target IP: ")

#define the scanner function and try to connect to the target IP and port
def scanner(port):
  try:
    sock.connect((target, port))
    return True
  except:
    return False

# Asking the user for the ports that they want to be scanned  
ports = input("Enter the ports to be scanned: ")    # User can enter as 100 122 123
ports_list = ports.split(' ')   # Splitting user input to get all the ports

#use for loop to state what ports are getting scanned, use scanner function to try and make a connection
try:
  for portNumber in ports_list:
    print("scanning port", portNumber)
    if scanner(portNumber ):
      print('[*] Port', portNumber, '/tcp', 'is open')
    else: 
      print('[*] Port', portNumber, '/tcp', 'is closed')
finally:
    pass
